# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:

# main
- package-ecosystem: "github-actions"
  target-branch: "main"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    actions-deps:
      patterns:
        - "*"

# develop
- package-ecosystem: "github-actions"
  target-branch: "develop"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    actions-deps:
      patterns:
        - "*"
